import { CryptoData, DetailedCryptoData } from "./type";

export const detailedCryptoData: DetailedCryptoData[] = [
  {
    name: "Bitcoin",
    symbol: "BTC",
    price: "$60,124.40",
    marketCap: "$1.2T",
    volume: "$790.7K",
    change24h: "+0.07%",
    changeType: "positive",
  },
  {
    name: "Ethereum",
    symbol: "ETH",
    price: "$2,559.66",
    marketCap: "$307.7B",
    volume: "$171.5K",
    change24h: "+1.17%",
    changeType: "positive",
  },
  {
    name: "Tether",
    symbol: "USDT",
    price: "$1.0002",
    marketCap: "$118.1B",
    volume: "$29.7K",
    change24h: "-0.01%",
    changeType: "negative",
  },
  {
    name: "Solana",
    symbol: "SOL",
    price: "$145.45",
    marketCap: "$67.8B",
    volume: "$2.4M",
    change24h: "-1.46%",
    changeType: "negative",
  },
  {
    name: "Shiba Inu",
    symbol: "SHIB",
    price: "$0.00001425",
    marketCap: "$8.4B",
    volume: "$165.1M",
    change24h: "+2.08%",
    changeType: "positive",
  },
  {
    name: "Chainlink",
    symbol: "LINK",
    price: "$11.26",
    marketCap: "$6.8B",
    volume: "$2.2K",
    change24h: "-0.44%",
    changeType: "negative",
  },
  {
    name: "Uniswap",
    symbol: "UNI",
    price: "$5.75",
    marketCap: "$4.5B",
    volume: "$1.1K",
    change24h: "+1.77%",
    changeType: "positive",
  },
  {
    name: "Polygon",
    symbol: "MATIC",
    price: "$0.4393",
    marketCap: "$4.1B",
    volume: "$1.3K",
    change24h: "+0.76%",
    changeType: "positive",
  },
  {
    name: "Pepe",
    symbol: "PEPE",
    price: "$0.00000798",
    marketCap: "$3.4B",
    volume: "$1.9K",
    change24h: "+0.38%",
    changeType: "positive",
  },
  {
    name: "Render",
    symbol: "RNDR",
    price: "$5.678",
    marketCap: "$2.2B",
    volume: "$81.9K",
    change24h: "-6.89%",
    changeType: "negative",
  },
  {
    name: "Aave",
    symbol: "AAVE",
    price: "$124.29",
    marketCap: "$1.9B",
    volume: "$763.9K",
    change24h: "+0.38%",
    changeType: "positive",
  },
];

export const cryptoData: CryptoData[] = [
  {
    pair: "MAX/USDC",
    price: "$0.3285",
    change: "-1.79%",
    changeType: "negative",
  },
  {
    pair: "CLOUD/USDC",
    price: "$0.1998",
    change: "+14.37%",
    changeType: "positive",
  },
  {
    pair: "AAVE/USDC",
    price: "$124.29",
    change: "+0.38%",
    changeType: "positive",
  },
  {
    pair: "LDO/USDC",
    price: "$0.00",
    change: "-",
    changeType: "neutral",
  },
  {
    pair: "MOTHER/USDC",
    price: "$0.0384",
    change: "-0.26%",
    changeType: "negative",
  },
];
